In [1]:
import numpy as np

# INDEXING AND SLICING

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [3]:
a1[-1]

9

In [4]:
a1[0]

0

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a2[1,2]

6

In [7]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
a3[1,0,1]

5

In [10]:
a3[1,1,1]

7

In [11]:
a1[2:5]

array([2, 3, 4])

In [12]:
a2[0,:]

array([0, 1, 2, 3])

In [13]:
a2[:,2]

array([ 2,  6, 10])

In [14]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [15]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
 a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [17]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [18]:
a3=np.arange(27).reshape(3,3,3)

In [19]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [20]:
a3[1,1,1]

13

In [21]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
 a3[0][1,:]

array([3, 4, 5])

In [24]:
a3[0][1,:]

array([3, 4, 5])

In [25]:
a3[0,1,:]

array([3, 4, 5])

In [26]:
a3[1,:,1]

array([10, 13, 16])

In [27]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])