In [1]:
import numpy as np

# Creating Numpy Array

In [ ]:
# Numpy is a python library that stands for "numerical python". It handles large datasets and perform numrical computations efficiently.It provides support for large datasets and perform numerical computation.

In [ ]:
# Numpy arrays can have multiple dimensions, allowing users to store data mulilayered structures.

In [2]:
arr = np.array(25) #OD Array
print(arr)

25


In [3]:
a = np.array([1,2,3])  # 1D Array
print(a)

[1 2 3]


In [4]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])  # 2D Array

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
# 3D Array = Tensor - storing a colour image 

In [4]:
import numpy as np
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [5]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [6]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# dtype

In [7]:
# You can specify the data type when creating a Numpy array using the dtype parameter. For ex-

In [8]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
np.array([1,2,0],dtype=bool)

array([ True,  True, False])

# arange()

In [ ]:
# arange function is used to create arrays with evenly spaced values.

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# reshape()

In [12]:
# used to change the shape of an array without altering its data.

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
ones() and zeros()

NameError: name 'ones' is not defined

In [15]:
# used to create arrays filled with 1 and 0 respectively

In [16]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# random.rand()

In [19]:
# Generate random no, random arrays

In [20]:
np.random.rand(3,2)

array([[0.3801844 , 0.12258725],
       [0.05507884, 0.48683557],
       [0.02104723, 0.06287491]])

In [21]:
np.random.uniform(1,10,(3,2))

array([[6.28436016, 6.42564724],
       [3.92386364, 9.96050626],
       [9.61078658, 9.8742466 ]])

# linspace()

In [23]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [24]:
np.linspace(0,15,12)

array([ 0.        ,  1.36363636,  2.72727273,  4.09090909,  5.45454545,
        6.81818182,  8.18181818,  9.54545455, 10.90909091, 12.27272727,
       13.63636364, 15.        ])

# identity()

In [27]:
np.identity(3)  # used to create identity matrix, diagonal values will be 1.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
a3 = np.arange(8).reshape(2,2,2) # two rows 2 columns and 2 matrices

In [31]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim # It prints no of dimensions

In [33]:
print(a3.ndim)

3


# shape # It shows shape

In [36]:
 a3.shape

(2, 2, 2)

# size # it prints no of elements.

In [37]:
a3.size

8

# itemsize # It shows size of each items

In [38]:
a3.itemsize

4

In [1]:
import numpy as np

In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [4]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
np.prod(c,axis=1)

array([[ 3,  8],
       [35, 48]])

In [7]:
np.max(c,axis=0)

array([[5, 6],
       [7, 8]])

In [9]:
np.prod(c,axis=1)

array([[ 3,  8],
       [35, 48]])

# mean()

In [10]:
np.mean(c)

4.5

In [11]:
np.mean(c,axis=0)

array([[3., 4.],
       [5., 6.]])

In [12]:
np.mean(c,axis=1)

array([[2., 3.],
       [6., 7.]])

# median()

In [13]:
np.median(c)

4.5

# std()

In [14]:
np.std(c)  # To calculate std deviation

2.29128784747792

# trignometric function

In [15]:
np.sin(c)

array([[[ 0.84147098,  0.90929743],
        [ 0.14112001, -0.7568025 ]],

       [[-0.95892427, -0.2794155 ],
        [ 0.6569866 ,  0.98935825]]])

In [16]:
np.log(c)

array([[[0.        , 0.69314718],
        [1.09861229, 1.38629436]],

       [[1.60943791, 1.79175947],
        [1.94591015, 2.07944154]]])

In [20]:
np.exp(c)

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [21]:
np.round(np.random((2,3))*100)  # this function round off the no.

TypeError: 'module' object is not callable

# Diff b\w round, floor and ceil

In [23]:
import math
x = 3.1
rounded_x = round(x)
floored_x = math.floor(x)
ceiled_x = math.ceil(x)
print("Original number:",x)
print("Rounded:",rounded_x)
print("floored:",floored_x)
print("ceiled:",ceiled_x)

Original number: 3.1
Rounded: 3
floored: 3
ceiled: 4


# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.